import postgres from 'postgres';

import { env } from '@/lib/server/env';

export const schemaStatements = [
  `CREATE TABLE IF NOT EXISTS categories (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, name TEXT NOT NULL, slug TEXT NOT NULL UNIQUE, sort_order INTEGER NOT NULL DEFAULT 0)`,
  `CREATE TABLE IF NOT EXISTS products (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, category_id INTEGER REFERENCES categories(id), slug TEXT NOT NULL UNIQUE, title TEXT NOT NULL, short_description TEXT NOT NULL, description TEXT NOT NULL, price_vnd INTEGER NOT NULL DEFAULT 0, license_note TEXT NOT NULL DEFAULT 'Giấy phép sử dụng tiêu chuẩn', status TEXT NOT NULL DEFAULT 'draft' CHECK(status IN ('draft','published','archived')), cover_tone TEXT NOT NULL DEFAULT 'indigo', created_at BIGINT NOT NULL, updated_at BIGINT NOT NULL, published_at BIGINT)`,
  `CREATE TABLE IF NOT EXISTS product_assets (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, product_id INTEGER NOT NULL REFERENCES products(id), version INTEGER NOT NULL, r2_key TEXT NOT NULL UNIQUE, original_filename TEXT NOT NULL, content_type TEXT NOT NULL, size_bytes INTEGER NOT NULL, sha256 TEXT NOT NULL, created_at BIGINT NOT NULL, UNIQUE(product_id, version))`,
  `CREATE TABLE IF NOT EXISTS product_images (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, product_id INTEGER NOT NULL REFERENCES products(id), r2_key TEXT NOT NULL UNIQUE, content_type TEXT NOT NULL, alt_text TEXT NOT NULL, sort_order INTEGER NOT NULL DEFAULT 0, created_at BIGINT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS users (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, email TEXT NOT NULL UNIQUE, created_at BIGINT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS otp_challenges (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, email TEXT NOT NULL, code_hash TEXT NOT NULL, ip_hash TEXT NOT NULL, expires_at BIGINT NOT NULL, attempts INTEGER NOT NULL DEFAULT 0, consumed_at BIGINT, created_at BIGINT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS sessions (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, user_id INTEGER NOT NULL REFERENCES users(id), token_hash TEXT NOT NULL UNIQUE, expires_at BIGINT NOT NULL, last_seen_at BIGINT NOT NULL, created_at BIGINT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS orders (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, order_code BIGINT NOT NULL UNIQUE, email TEXT NOT NULL, user_id INTEGER REFERENCES users(id), status TEXT NOT NULL DEFAULT 'pending' CHECK(status IN ('pending','paid','cancelled','expired','refunded')), amount_total INTEGER NOT NULL, payos_payment_link_id TEXT, delivery_status TEXT NOT NULL DEFAULT 'pending' CHECK(delivery_status IN ('pending','sent','failed')), delivery_error TEXT, created_at BIGINT NOT NULL, paid_at BIGINT)`,
  `CREATE TABLE IF NOT EXISTS order_items (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, order_id INTEGER NOT NULL REFERENCES orders(id), product_id INTEGER NOT NULL REFERENCES products(id), asset_id INTEGER NOT NULL REFERENCES product_assets(id), title_snapshot TEXT NOT NULL, price_snapshot INTEGER NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS entitlements (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, order_item_id INTEGER NOT NULL UNIQUE REFERENCES order_items(id), user_id INTEGER REFERENCES users(id), email TEXT NOT NULL, created_at BIGINT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS download_links (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, order_item_id INTEGER NOT NULL REFERENCES order_items(id), token_hash TEXT NOT NULL UNIQUE, email TEXT NOT NULL, expires_at BIGINT NOT NULL, max_downloads INTEGER NOT NULL DEFAULT 5, download_count INTEGER NOT NULL DEFAULT 0, created_at BIGINT NOT NULL)`,
  `CREATE TABLE IF NOT EXISTS download_events (id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY, link_id INTEGER NOT NULL REFERENCES download_links(id), ip_hash TEXT NOT NULL, user_agent TEXT NOT NULL, created_at BIGINT NOT NULL)`,
  `CREATE INDEX IF NOT EXISTS idx_products_status_category ON products(status, category_id)`,
  `CREATE INDEX IF NOT EXISTS idx_product_images_product_sort ON product_images(product_id, sort_order)`,
  `CREATE INDEX IF NOT EXISTS idx_otp_email_created ON otp_challenges(email, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_sessions_user ON sessions(user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_orders_email_created ON orders(email, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_orders_status_created ON orders(status, created_at)`,
  `CREATE INDEX IF NOT EXISTS idx_order_items_order ON order_items(order_id)`,
  `CREATE INDEX IF NOT EXISTS idx_entitlements_email ON entitlements(email)`,
  `CREATE INDEX IF NOT EXISTS idx_entitlements_user ON entitlements(user_id)`,
  `CREATE INDEX IF NOT EXISTS idx_download_events_link ON download_events(link_id)`,
];

export type QueryMeta = { changes: number; last_row_id?: number };

let client: ReturnType<typeof postgres> | undefined;

export function getPostgresClient() {
  if (!client) {
    if (!env.POSTGRES_URL) throw new Error('POSTGRES_URL chưa được cấu hình.');
    client = postgres(env.POSTGRES_URL, { prepare: false, types: { bigint: postgres.BigInt } });
  }
  return client;
}

function normalizeValue(value: unknown): unknown {
  if (typeof value === 'bigint') return Number(value);
  if (Array.isArray(value)) return value.map(normalizeValue);
  if (value && typeof value === 'object') {
    return Object.fromEntries(Object.entries(value).map(([key, item]) => [key, normalizeValue(item)]));
  }
  return value;
}

function compileQuery(source: string, returnId: boolean) {
  let query = source.trim().replace(/;$/, '');
  const ignoreConflict = /^INSERT\s+OR\s+IGNORE\s+INTO\b/i.test(query);
  query = query.replace(/^INSERT\s+OR\s+IGNORE\s+INTO\b/i, 'INSERT INTO');
  let parameter = 0;
  query = query.replace(/\?/g, () => `$${++parameter}`);
  if (ignoreConflict) query += ' ON CONFLICT DO NOTHING';
  if (returnId && /^INSERT\s+INTO\b/i.test(query) && !/\bRETURNING\b/i.test(query)) query += ' RETURNING id';
  return query;
}

export class PreparedQuery {
  private values: unknown[] = [];

  constructor(private readonly source: string) {}

  bind(...values: unknown[]) {
    const query = new PreparedQuery(this.source);
    query.values = values;
    return query;
  }

  private async execute(returnId = false) {
    const rows = await getPostgresClient().unsafe(compileQuery(this.source, returnId), this.values as never[]);
    return { rows: Array.from(rows, (row) => normalizeValue(row) as Record<string, unknown>), count: rows.count };
  }

  async first<T>() {
    const result = await this.execute();
    return (result.rows[0] as T | undefined) ?? null;
  }

  async all<T>() {
    const result = await this.execute();
    return { results: result.rows as T[] };
  }

  async run() {
    const result = await this.execute(true);
    const id = result.rows[0]?.id;
    return { meta: { changes: result.count, ...(typeof id === 'number' ? { last_row_id: id } : {}) } satisfies QueryMeta };
  }
}

class DatabaseCompat {
  prepare(source: string) { return new PreparedQuery(source); }

  async batch(statements: PreparedQuery[]) {
    const results = [];
    for (const statement of statements) results.push(await statement.run());
    return results;
  }
}

const database = new DatabaseCompat();
export function getDatabaseCompat() { return database; }
